---

# Which states to track
# Possible values: one of the ones listet at https://api.presseportal.de/doc/value/region
STATE_FILTER:
  - nrw

#ToDo: update-db so anpassen, dass mehr als nur ein Staat gleichzeitig abgefragt werden kann

# Polling rate for checking api
# Possible values: int (seconds)
DELAY:
  - 300

# Amount of stories to download per api call
# Possible values: any number between 1 and 50 (maximum accepted number by api is 50)
DOWNLOAD_LIMIT:
  - 50